# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fergal's 1st Jekyll Website
email: fergaldowney@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  My first attempt at using Jekyll to create a basic page and hosting it on GitHub Pages. Updated with a build script.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://f3rgl.github.io" # the base hostname & protocol for your site
twitter_username: f3rgl
github_username:  f3rgl

# Build settings
markdown: kramdown
